### ISSUE TITLE
App refuses to display output when there are warnings from stderr

### ISSUE THREAD

**Issue by DGCK81LNN** [lojban/jboski#1]
I really love this new jbofihe port but here's an issue that I've spotted, hope it gets fixed.

Sometimes jbofihe reports warnings in stderr and still gives output, e.g. when a sentence contains only a sumti:
```
ma gleki .i la vrude
            ^
```

```
Warning: Sentence may be missing selbri at line 1 column 13?
```

The current jboski seems to return an error as long as there is anything in stderr.

**Comment by DGCK81LNN** [comment]
It would be nice if the output could still be shown when there are warnings.

**Comment by ghost** [comment]
@rlpowell @lagleki please fix this the website has been broken for months

**Comment by rlpowell** [comment]
I wouldn't call that "broken", like, at all, since all normal sentences work, but I'll take a look.

**Comment by ghost** [comment]
> I wouldn't call that "broken", like, at all, since all normal sentences work, but I'll take a look.

No, some normal sentences do not work. Answers to ma-questions, for example, normally do not contain a selbri, and do not work. Sentences with jai used for abstraction also do not work and are also normal Lojban.

**Comment by rlpowell** [comment]
Yeah, that's still not what "the website has been broken for months" means.

**Comment by ghost** [comment]
Functionality it used to have has been gone for months. I'd call that broken.

**Comment by rlpowell** [comment]
OK, well, as someone who professionally maintains websites for a living, "broken" is "the page doesn't load", and it offends my professional sensibilities that you'd describe this problem that way, implying that I've been letting the site be totally non-functional for months on end.

But if you'd prefer I *not* investigate, by all means, keep arguing.

**Comment by ghost** [comment]
> OK, well, as someone who professionally maintains websites for a living, "broken" is "the page doesn't load", and it offends my professional sensibilities that you'd describe this problem that way, implying that I've been letting the site be totally non-functional for months on end.
> 
> But if you'd prefer I _not_ investigate, by all means, keep arguing.

I've closed my other issue about this. While the page has loaded so broken isn't the right word, you have allowed grammatical Lojban to fail for months. Looking at the python code involved in generating the output, it looks like it'd be a simple change of one or two lines but I don't know how to test changes myself.

**Comment by rlpowell** [comment]
@samflir As a *volunteer* who first became aware of this issue within the last two hours, I find your continued insistence that I suck to be profoundly rude.  I considered simply not fixing this issue just because of that, but that's not fair to the rest of the community.  Please try not to treat volunteers in this way in the future.

@DGCK81LNN You're quite correct, it was unconditionally failing when anything was in stderr.

Fixed in https://github.com/lojban/jboski/commit/55d39080b86662f4c9e467d9303d31197f64f70f , and also in production.

**Comment by ghost** [comment]
sorry I got impatient and thank you for the fix

**Comment by DGCK81LNN** [comment]
Thanks for the fix.
