### ISSUE TITLE
GoogleAPIs doesn't work in mainland China, causing jQuery not loading

### ISSUE THREAD

**Issue by DGCK81LNN** [lojban/jboski#2]
Another thing. I understand that in most cases GoogleAPIs is among the best ways to invoke jQuery, but it currently doesn't work at all here in mainland China due to censorship. Any chance to switch to another CDN?

**Comment by lagleki** [comment]
Which one?

**Comment by lagleki** [comment]
replaced with 
```
<script type="text/javascript" src="https://code.jquery.com/jquery-1.5.1.min.js"></script>
```
Please, reopen the issue if anything is wrong.

**Comment by DGCK81LNN** [comment]
Huge thanks, it works.
