### ISSUE TITLE
This website has been broken for ages

### ISSUE THREAD

**Issue by ghost** [lojban/jboski#4]
jboski producing error messages does not necessarily indicate invalid Lojban, so the parsed text should still be shown. This happens when a sentence does not have a selbri or when jai is used on its own for abstraction like in sentences such as ".i mi jai ciska". Both are fully grammatical Lojban according to the CLL.

The old interface would show both error messages and parsed output when an error message was present, which was much more usable and would reliably parse grammatical Lojban, no matter what that grammatical Lojban was.

I know there's another issue for this but this problem has remained unfixed for months and was introduced when the new interface was released. I'm certain it'd be a simple fix.

**Comment by rlpowell** [comment]
For posterity, see #1
